name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.0.0
      with:
        gitversion-version: 5.1.1
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.0.0
      with:
        useConfigFile: true
        configFilePath: ./.github/gitversion.yml
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
#   - name: Test
#     run: dotnet test --no-build --verbosity normal
    - name: Package NuGet
      run: dotnet pack --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
    - name: Push NuGet to GitHub registry
      run: dotnet nuget push ./package/*.nupkg --source https://nuget.pkg.github.com/CheesyTot/index.json --api-key ${{ github.token }}
